<template>
  <div class="simple-report">
    <!-- 使用 ReportViewer 渲染 Markdown -->
    <ReportViewer 
      ref="reportViewerRef"
      :markdown="markdownContent" 
      :title="reportTitle"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import ReportViewer from '@/components/reports/ReportViewer.vue'

const { t } = useI18n()

// 获取 ReportViewer 组件引用
const reportViewerRef = ref()

interface AnalysisThought {
  agent?: string
  thought: string
  timestamp: string
  phase?: string
  phaseName?: string
  isTool?: boolean
  tool?: string
}

interface Analysis {
  id: string
  timestamp: number
  duration: number
  config: {
    symbol: string
    marketType?: string
    depth?: number
  }
  agentThoughts: AnalysisThought[]
}

interface Props {
  analysis: Analysis | null
}

const props = defineProps<Props>()

// 报告标题
const reportTitle = computed(() => {
  return `${props.analysis?.config?.symbol || ''} ${t('report.reportTitle')}`
})

// 转换为 Markdown 格式
const markdownContent = computed(() => {
  if (!props.analysis?.agentThoughts || props.analysis.agentThoughts.length === 0) {
    return `## ${t('report.analysisProcess')}\n\n> ${t('report.noDataFound')}`
  }

  // 生成报告头部信息
  const header = `## ${t('report.basicInfo')}

| ${t('report.project')} | ${t('report.value')} |
|------|-----|
| ${t('report.fields.analysisId')} | \`${props.analysis.id?.slice(-8) || 'N/A'}\` |
| ${t('report.fields.analysisTime')} | ${new Date(props.analysis.timestamp).toLocaleString()} |
| ${t('report.fields.analysisDepth')} | ${props.analysis.config?.depth || 1} |
| ${t('report.fields.analysisDuration')} | ${formatDuration(props.analysis.duration)} |

---

## ${t('report.analysisProcess')}

`

  // 处理分析步骤
  const steps = props.analysis.agentThoughts
    .map((thought, index) => {
      const timestamp = new Date(thought.timestamp).toLocaleTimeString()
      const agent = thought.agent || t('common.system')
      const phase = thought.phaseName || thought.phase || ''
      
      // 根据代理类型使用不同的图标
      const agentIcon = getAgentIcon(agent)
      
      return `### ${agentIcon} ${t('report.step')} ${index + 1}: ${agent}${phase ? ` - ${phase}` : ''}

**${t('report.time')}**: \`${timestamp}\`

${formatThoughtContent(thought.thought)}

---`
    })
    .join('\n\n')

  return header + steps + `

## ${t('report.generationInfo')}

> 📄 ${t('report.autoGenerated')}  
> 🕐 ${t('report.generatedAt')}: ${new Date().toLocaleString()}`
})

// 格式化分析内容，保持代码块和列表格式
const formatThoughtContent = (content: string) => {
  if (!content) return ''
  
  // 处理多行内容，保持原有的结构
  return content
    .split('\n')
    .map(line => {
      // 如果行以特殊字符开始，可能是列表或代码
      if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
        return line
      }
      if (line.trim().startsWith('#')) {
        return line.replace(/^#+\s*/, '**') + '**'
      }
      return line
    })
    .join('\n')
}

// 根据代理获取对应图标
const getAgentIcon = (agent: string) => {
  const icons: Record<string, string> = {
    // 中文
    '系统': '🔧',
    '市场分析师': '📊',
    '数据分析': '📈',
    '技术分析': '🔍',
    '投资建议': '💡',
    '组合经理': '💼',
    '风险经理': '⚠️',
    '交易员': '💹',
    // English
    'System': '🔧',
    'Market Analyst': '📊',
    'News Analyst': '📰',
    'Social Media Analyst': '📱',
    'Bear Researcher': '🐻',
    'Bull Researcher': '🐂',
    'Research Manager': '📋',
    'Portfolio Manager': '💼',
    'Risk Manager': '⚠️',
    'Trader': '💹'
  }
  return icons[agent] || '🤖'
}

// 格式化持续时间
const formatDuration = (duration: number | undefined) => {
  if (!duration) return t('report.duration.unknown')
  const seconds = Math.floor(duration / 1000)
  if (seconds < 60) {
    return t('report.duration.seconds', { seconds })
  } else {
    const minutes = Math.floor(seconds / 60)
    const remainingSeconds = seconds % 60
    return t('report.duration.minutesSeconds', { minutes, seconds: remainingSeconds })
  }
}

// 导出打印方法给父组件使用
const print = () => {
  if (reportViewerRef.value) {
    reportViewerRef.value.print()
  }
}

// 暴露方法给父组件
defineExpose({ print })

</script>

<style scoped>
.simple-report {
  width: 100%;
  height: 100%;
}
</style>