"""Add role and user_metadata fields

Revision ID: 02c4f9202d5c
Revises: ad760e705316
Create Date: 2025-07-29 03:41:24.702523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c4f9202d5c'
down_revision: Union[str, None] = 'ad760e705316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('user_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_metadata')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
